### ISSUE TITLE
Crushing in chunk load?

### ISSUE THREAD

**Issue by HinyariGohan** [OpenMods/OpenModsLib#67] opened 2017-06-30 15:33 UTC
Mod had crushed when I was loading chunks.

```
> ---- Minecraft Crash Report ----
> 
> WARNING: coremods are present:
>   CoFH Loading Plugin (CoFHCore-1.10.2-4.1.9.13-universal.jar)
>   CoreMod (Aroma1997Core-1.9.4-1.1.1.2.jar)
>   OpenModsCorePlugin (OpenModsLib-1.10.2-0.10-1.10.X-snapshot-33.jar)
>   FMLPlugin (InventoryTweaks-1.62-dev-66.jar)
>   Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.3-anarchy.jar)
>   EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
>   IC2core (industrialcraft-2-2.6.244-ex110.jar)
>   MicdoodlePlugin (MicdoodleCore-1.10.2-4.0.0.107.jar)
>   NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.220-universal.jar)
>   CXLibraryCore (cxlibrary-1.10.2-1.2.3.jar)
>   CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.267-universal.jar)
>   AppEngCore (appliedenergistics2-rv4-alpha-11.jar)
>   IntelliInputCorePlugin (IntelliInput-2.5-for1.10.2.jar)
> Contact their authors BEFORE contacting forge
> 
> // I let you down. Sorry :(
> 
> Time: 17/07/01 0:24
> Description: Ticking block entity
> 
> java.lang.NullPointerException: Ticking block entity
> 	at openmods.utils.NetUtils.getPlayersWatchingChunk(NetUtils.java:42)
> 	at openmods.utils.NetUtils.getPlayersWatchingBlock(NetUtils.java:48)
> 	at openmods.sync.SyncMapTile.getPlayersWatching(SyncMapTile.java:48)
> 	at openmods.sync.SyncMapServer$AutomaticInitialPacketStrategy.sendUpdates(SyncMapServer.java:171)
> 	at openmods.sync.SyncMapServer.sendUpdates(SyncMapServer.java:262)
> 	at openmods.tileentity.SyncedTileEntity.sync(SyncedTileEntity.java:111)
> 	at openblocks.common.tileentity.TileEntityTank.func_73660_a(TileEntityTank.java:349)
> 	at net.minecraft.world.World.func_72939_s(World.java:1804)
> 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
> 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
> 	at java.lang.Thread.run(Unknown Source)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Server thread
> Stacktrace:
> 	at openmods.utils.NetUtils.getPlayersWatchingChunk(NetUtils.java:42)
> 	at openmods.utils.NetUtils.getPlayersWatchingBlock(NetUtils.java:48)
> 	at openmods.sync.SyncMapTile.getPlayersWatching(SyncMapTile.java:48)
> 	at openmods.sync.SyncMapServer$AutomaticInitialPacketStrategy.sendUpdates(SyncMapServer.java:171)
> 	at openmods.sync.SyncMapServer.sendUpdates(SyncMapServer.java:262)
> 	at openmods.tileentity.SyncedTileEntity.sync(SyncedTileEntity.java:111)
> 	at openblocks.common.tileentity.TileEntityTank.func_73660_a(TileEntityTank.java:349)
> 
> -- Block entity being ticked --
> Details:
> 	Name: openblocks_tank // openblocks.common.tileentity.TileEntityTank
> 	Block type: ID #1456 (tile.openblocks.tank // openblocks.common.block.BlockTank)
> 	Block data value: 0 / 0x0 / 0b0000
> 	Block location: World: (-146,71,56), Chunk: (at 14,4,8 in -10,3; contains blocks -160,0,48 to -145,255,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
> 	Actual block type: ID #1456 (tile.openblocks.tank // openblocks.common.block.BlockTank)
> 	Actual block data value: 0 / 0x0 / 0b0000
> Stacktrace:
> 	at net.minecraft.world.World.func_72939_s(World.java:1804)
> 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
> 
> -- Affected level --
> Details:
> 	Level name: うんちもりもり
> 	All players: 1 total; [GCEntityPlayerMP['Hinyari_Gohan'/879, l='うんちもりもり', x=-275.68, y=72.92, z=-142.47]]
> 	Chunk stats: ServerChunkCache: 634 Drop: 47
> 	Level seed: 100893702
> 	Level generator: ID 00 - default, ver 1. Features enabled: true
> 	Level generator options: 
> 	Level spawn location: World: (-140,64,104), Chunk: (at 4,4,8 in -9,6; contains blocks -144,0,96 to -129,255,111), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
> 	Level time: 6441261 game time, 6921418 day time
> 	Level dimension: 0
> 	Level storage version: 0x04ABD - Anvil
> 	Level weather: Rain time: 2185 (now: true), thunder time: 7857 (now: false)
> 	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
> Stacktrace:
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
> 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
> 	at java.lang.Thread.run(Unknown Source)
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.10.2
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 1.8.0_131, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 838996992 bytes (800 MB) / 2118914048 bytes (2020 MB) up to 4281597952 bytes (4083 MB)
> 	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
> 	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
> 	FML: MCP 9.32 Powered by Forge 12.18.3.2316 Optifine OptiFine_1.10.2_HD_U_D8 81 mods loaded, 81 mods active
> 	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
> 	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
> 	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2316.jar) 
> 	UCHIJAAAA	Forge{12.18.3.2316} [Minecraft Forge] (forge-1.10.2-12.18.3.2316.jar) 
> 	UCHIJAAAA	appliedenergistics2-core{rv4-alpha-11} [Applied Energistics 2 Core] (minecraft.jar) 
> 	UCHIJAAAA	Aroma1997Core{${version}} [Aroma1997Core] (Aroma1997Core-1.9.4-1.1.1.2.jar) 
> 	UCHIJAAAA	intelliinput{2.5} [IntelliInput for 1.10.2] (minecraft.jar) 
> 	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
> 	UCHIJAAAA	NotEnoughItems{2.1.3.220} [Not Enough Items] (NotEnoughItems-1.10.2-2.1.3.220-universal.jar) 
> 	UCHIJAAAA	openmodscore{0.10} [OpenModsLib Core] (minecraft.jar) 
> 	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
> 	UCHIJAAAA	foamfixcore{7.7.4} [FoamFixCore] (minecraft.jar) 
> 	UCHIJAAAA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.9.267-universal.jar) 
> 	UCHIJAAAA	net.minecraft.scalar.cutall.mod_CutAllSMP{2.5.2} [CutAllSMP] (%5B1.10.2%5D%5Bforge2014%5Dmod_CutAllSMP_v2.5.2.zip) 
> 	UCHIJAAAA	net.minecraft.scalar.mineall.mod_MineAllSMP{2.6.5} [MineAllSMP] (%5B1.10.2%5D%5Bforge2014%5Dmod_MineAllSMP_v2.6.5.zip) 
> 	UCHIJAAAA	net.minecraft.scalar.pickupwidely.mod_PickupWidelySMP{1.2.3} [PickupWidelySMP] (%5B1.10.2%5D%5Bforge2014%5Dmod_PickupWidelySMP_v1.2.3.zip) 
> 	UCHIJAAAA	net.minecraft.rosettaenchanttable{0.0.5} [Rosetta Enchant Table] (%5B1.10.2%5D%5Bforge2014%5Dmod_RosettaEnchantTable_v0.0.5.zip) 
> 	UCHIJAAAA	storagebox{3.1.1} [StorageBox] (%5B1.10.2%5D%5Bforge2014%5Dmod_StorageBox_v3.1.1.zip) 
> 	UCHIJAAAA	silkspawners{1.1} [Silk Spawners] ([1.10.2]SilkSpawners Beta1.2.jar) 
> 	UCHIJAAAA	appliedenergistics2{rv4-alpha-11} [Applied Energistics 2] (appliedenergistics2-rv4-alpha-11.jar) 
> 	UCHIJAAAA	Aroma1997CoreHelper{1.1.1.2} [Aroma1997Core|Helper] (Aroma1997Core-1.9.4-1.1.1.2.jar) 
> 	UCHIJAAAA	AromaBackup{1.0.1.1} [AromaBackup] (AromaBackup-1.9.4-1.0.1.1.jar) 
> 	UCHIJAAAA	AromaBackupRecovery{1.0} [AromaBackup Recovery] (AromaBackup-1.9.4-1.0.1.1.jar) 
> 	UCHIJAAAA	bamboomod{Minecraft1.10.2 var3.0.0.12.2} [bamboomod] (Bamboo-3.0.0.12.2.jar) 
> 	UCHIJAAAA	bedrocklayer{1.2.1} [BedrockLayer] (BedrockLayer_1.9.4-v1.2.1.jar) 
> 	UCHIJAAAA	Chameleon{1.10.2-2.3.0} [Chameleon] (Chameleon-1.10.2-2.3.0.jar) 
> 	UCHIJAAAA	ChestTransporter{2.5.17} [Chest Transporter] (ChestTransporter-1.10.2-2.5.17.jar) 
> 	UCHIJAAAA	CodeChickenLib{2.5.9.267} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.9.267-universal.jar) 
> 	UCHIJAAAA	CodeChickenCore{2.4.1.103} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.1.103-universal.jar) 
> 	UCHIJAAAA	cofhcore{4.1.9} [CoFH Core] (CoFHCore-1.10.2-4.1.9.13-universal.jar) 
> 	UCHIJAAAA	IC2{2.6.244-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.244-ex110.jar) 
> 	UCHIJAAAA	compactsolars{1.10.2-5.0.9.332} [Compact Solar Arrays] (CompactSolars-1.10.2-5.0.9.332-universal.jar) 
> 	UCHIJAAAA	cookingforblockheads{4.2.43} [Cooking for Blockheads] (CookingForBlockheads_1.10.2-4.2.43.jar) 
> 	UCHIJAAAA	craftingex{1.1.1} [Crafting EX] (CraftingEX_1.9.4-v1.1.1.jar) 
> 	UCHIJAAAA	cxlibrary{1.2.3} [CXLibrary] (cxlibrary-1.10.2-1.2.3.jar) 
> 	UCHIJAAAA	endercore{1.10.2-0.4.1.66-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.66-beta.jar) 
> 	UCHIJAAAA	JEI{3.14.7.419} [Just Enough Items] (jei_1.10.2-3.14.7.419.jar) 
> 	UCHIJAAAA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
> 	UCHIJAAAA	EnderIO{1.10.2-3.1.193} [Ender IO] (EnderIO-1.10.2-3.1.193.jar) 
> 	UCHIJAAAA	EnderStorage{2.2.1.106} [EnderStorage] (EnderStorage-1.10.2-2.2.1.106-universal.jar) 
> 	UCHIJAAAA	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.10.2-1.4.3.jar) 
> 	UCHIJAAAA	foamfix{@VERSION@} [FoamFix] (foamfix-0.6.3-anarchy.jar) 
> 	UCHIJAAAA	forestry{5.2.17.376} [Forestry] (forestry_1.10.2-5.2.17.376.jar) 
> 	UCHIJAAAA	galacticraftcore{4.0.0} [Galacticraft Core] (GalacticraftCore-1.10.2-4.0.0.107.jar) 
> 	UCHIJAAAA	galacticraftplanets{4.0.0} [Galacticraft Planets] (Galacticraft-Planets-1.10.2-4.0.0.107.jar) 
> 	UCHIJAAAA	fishing{1.4.4} [Fishing Net Mod] (GiacomosFishingNet1.10.2-1.4.4.jar) 
> 	UCHIJAAAA	GraveStone{1.0.6} [GraveStone] (GraveStone-1.10.2-Graves-1.0.6.jar) 
> 	UCHIJAAAA	inventorytweaks{1.62-dev-66-c082db3} [Inventory Tweaks] (InventoryTweaks-1.62-dev-66.jar) 
> 	UCHIJAAAA	ironbackpacks{1.10.2-2.2.27} [Iron Backpacks] (IronBackpacks-1.10.2-2.2.27.jar) 
> 	UCHIJAAAA	ironchest{1.10.2-7.0.15.804} [Iron Chest] (ironchest-1.10.2-7.0.15.804.jar) 
> 	UCHIJAAAA	journeymap{1.10.2-5.4.7} [JourneyMap] (journeymap-1.10.2-5.4.7.jar) 
> 	UCHIJAAAA	jeresources{0.5.8.98} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.8.98.jar) 
> 	UCHIJAAAA	LotsOfFood{1.12.0} [Lots of Food] (Lots of Food-1.12.0.jar) 
> 	UCHIJAAAA	mantle{1.10.2-1.1.5.205} [Mantle] (Mantle-1.10.2-1.1.5.jar) 
> 	UCHIJAAAA	McAssistant{1.10.2-1.1} [McAssistant] (McAssistant-1.10.2-1.1.jar) 
> 	UCHIJAAAA	mcmultipart{1.4.0} [MCMultiPart] (MCMultiPart-1.4.0-universal.jar) 
> 	UCHIJAAAA	Mekanism{9.2.2} [Mekanism] (Mekanism-1.10.2-9.2.2.301.jar) 
> 	UCHIJAAAA	MekanismGenerators{9.2.2} [MekanismGenerators] (MekanismGenerators-1.10.2-9.2.2.301.jar) 
> 	UCHIJAAAA	MekanismTools{9.2.2} [MekanismTools] (MekanismTools-1.10.2-9.2.2.301.jar) 
> 	UCHIJAAAA	minefactoryreloaded{2.9.0B1} [MineFactory Reloaded] (MineFactoryReloaded-[1.10.2]2.9.0B1-224.jar) 
> 	UCHIJAAAA	MineFactoryReloaded|CompatVanilla{2.9.0B1} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.10.2]2.9.0B1-224.jar) 
> 	UCHIJAAAA	numina{1.4.0} [numina] (ModularPowersuits-1.10.2-1.2.123.jar) 
> 	UCHIJAAAA	powersuits{1.10.2-1.2.123} [MachineMuse's Modular Powersuits] (ModularPowersuits-1.10.2-1.2.123.jar) 
> 	UCHIJAAAA	morefood{1.17} [More Foods] (more-foods-1.10.2-2011-1.17.jar) 
> 	UCHIJAAAA	MultiPageChest{1.7.3} [Multi Page Chest] (MultiPageChest-1.10.2-1.7.3.jar) 
> 	UCHIJAAAA	nethercore{1.10.2-2.0.3} [Nether Core] (nethercore-1.10.2-2.0.3.jar) 
> 	UCHIJAAAA	openmods{0.10} [OpenModsLib] (OpenModsLib-1.10.2-0.10-1.10.X-snapshot-33.jar) 
> 	UCHIJAAAA	openblocks{1.6} [OpenBlocks] (OpenBlocks-1.10.2-1.6-1.10.X-snapshot-33.jar) 
> 	UCHIJAAAA	harvestcraft{1.10.2j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.10.2j.jar) 
> 	UCHIJAAAA	railcraft{10.1.2} [Railcraft] (Railcraft_1.10.2-10.1.2.jar) 
> 	UCHIJAAAA	flammpfeil.slashblade{mc1.10.2-r35} [SlashBlade] (SlashBlade-mc1.10.2-r35.jar) 
> 	UCHIJAAAA	SolidXp{1.1.2} [SolidXp] (SolidXp-1.1.2.jar) 
> 	UCHIJAAAA	spawnchecker{2.5.1.134} [SpawnChecker] (SpawnChecker-2.5.1.134.jar) 
> 	UCHIJAAAA	spawnchecker.presetmode{2.5.1.134} [SpawnChecker preset mode] (SpawnChecker-2.5.1.134.jar) 
> 	UCHIJAAAA	StorageDrawers{1.10.2-3.7.9} [Storage Drawers] (StorageDrawers-1.10.2-3.7.9.jar) 
> 	UCHIJAAAA	tconstruct{1.10.2-2.6.5.10} [Tinkers' Construct] (TConstruct-1.10.2-2.6.5.jar) 
> 	UCHIJAAAA	thermalfoundation{2.1.2} [Thermal Foundation] (ThermalFoundation-1.10.2-2.1.2.4-universal.jar) 
> 	UCHIJAAAA	thermalexpansion{5.1.5} [Thermal Expansion] (ThermalExpansion-1.10.2-5.1.5.6-universal.jar) 
> 	UCHIJAAAA	thermaldynamics{2.0.6} [Thermal Dynamics] (ThermalDynamics-1.10.2-2.0.6.8-universal.jar) 
> 	UCHIJAAAA	tinkertoolleveling{1.10.2-1.0.1.DEV.f5def58} [Tinkers Tool Leveling] (TinkerToolLeveling-1.10.2-1.0.1.jar) 
> 	UCHIJAAAA	torohealthmod{1.10.2-7} [ToroHealth Damage Indicators] (torohealth-1.10.2-7.jar) 
> 	UCHIJAAAA	waystones{2.0.12} [Waystones] (Waystones_1.10.2-2.0.12.jar) 
> 	Loaded coremods (and transformers): 
> CoFH Loading Plugin (CoFHCore-1.10.2-4.1.9.13-universal.jar)
>   cofh.asm.CoFHClassTransformer
>   cofh.asm.repack.codechicken.lib.asm.ClassHierarchyManager
> CoreMod (Aroma1997Core-1.9.4-1.1.1.2.jar)
>   
> OpenModsCorePlugin (OpenModsLib-1.10.2-0.10-1.10.X-snapshot-33.jar)
>   openmods.core.OpenModsClassTransformer
> FMLPlugin (InventoryTweaks-1.62-dev-66.jar)
>   invtweaks.forge.asm.ContainerTransformer
> Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.3-anarchy.jar)
>   pl.asie.foamfix.coremod.FoamFixTransformer
> EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
>   com.enderio.core.common.transform.EnderCoreTransformer
> IC2core (industrialcraft-2-2.6.244-ex110.jar)
>   
> MicdoodlePlugin (MicdoodleCore-1.10.2-4.0.0.107.jar)
>   micdoodle8.mods.miccore.MicdoodleTransformer
> NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.220-universal.jar)
>   codechicken.nei.asm.NEITransformer
> CXLibraryCore (cxlibrary-1.10.2-1.2.3.jar)
>   cubex2.cxlibrary.CoreModTransformer
> CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.267-universal.jar)
>   codechicken.lib.asm.ClassHeirachyManager
>   codechicken.lib.asm.CCL_ASMTransformer
> AppEngCore (appliedenergistics2-rv4-alpha-11.jar)
>   appeng.coremod.transformer.ASMIntegration
> IntelliInputCorePlugin (IntelliInput-2.5-for1.10.2.jar)
>   com.tsoft_web.IntelliInput.asm.IntelliInputTransformer
> 	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
> 	OpenModsLib class transformers: [movement_callback:FINISHED],[player_damage_hook:FINISHED],[map_gen_fix:FINISHED],[player_render_hook:FINISHED]
> 	Class transformer null safety: all safe
> 	AE2 Version: alpha rv4-alpha-11 for Forge 12.18.3.2185
> 	minefactoryreloaded: -[1.10.2]2.9.0B1-224
> 	Pulsar/tconstruct loaded Pulses: 
> 		- TinkerCommons (Enabled/Forced)
> 		- TinkerWorld (Enabled/Not Forced)
> 		- TinkerTools (Enabled/Not Forced)
> 		- TinkerHarvestTools (Enabled/Forced)
> 		- TinkerMeleeWeapons (Enabled/Forced)
> 		- TinkerRangedWeapons (Enabled/Forced)
> 		- TinkerModifiers (Enabled/Forced)
> 		- TinkerSmeltery (Enabled/Not Forced)
> 		- TinkerGadgets (Enabled/Not Forced)
> 		- TinkerOredict (Enabled/Forced)
> 		- TinkerIntegration (Enabled/Forced)
> 		- TinkerFluids (Enabled/Forced)
> 		- TinkerMaterials (Enabled/Forced)
> 		- TinkerModelRegister (Enabled/Forced)
> 		- WailaIntegration (Enabled/Not Forced)
> 
> 	NotEnoughItems Invalid Fingerprint Reports: 
> 	CodeChickenLib Invalid Fingerprint Reports: 
> 	CodeChickenCore Invalid Fingerprint Reports: 
> 	EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
>                   * Optifine is installed. This is NOT supported.
>                   * An unsupportted RF API is installed (1.7.0 from (guessing) jar:file:/F:/.minecraft/versions/1.10.2-Mod-Local/mods/CoFHCore-1.10.2-4.1.9.13-universal.jar!/cofh/api/CoFHAPIProps.class).
>                     Ender IO needs at least 1.4.0 and will NOT work with older versions.
>                  This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
> 	Detailed RF API diagnostics:
>                   * RF API class 'EnergyStorage' is loaded from: jar:file:/F:/.minecraft/versions/1.10.2-Mod-Local/mods/CoFHCore-1.10.2-4.1.9.13-universal.jar!/cofh/api/energy/EnergyStorage.class
>                   * RF API class 'IEnergyConnection' is loaded from: jar:file:/F:/.minecraft/versions/1.10.2-Mod-Local/mods/CoFHCore-1.10.2-4.1.9.13-universal.jar!/cofh/api/energy/IEnergyConnection.class
>                   * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/F:/.minecraft/versions/1.10.2-Mod-Local/mods/CoFHCore-1.10.2-4.1.9.13-universal.jar!/cofh/api/energy/IEnergyContainerItem.class
>                   * RF API class 'IEnergyHandler' is loaded from: jar:file:/F:/.minecraft/versions/1.10.2-Mod-Local/mods/CoFHCore-1.10.2-4.1.9.13-universal.jar!/cofh/api/energy/IEnergyHandler.class
>                   * RF API class 'IEnergyProvider' is loaded from: jar:file:/F:/.minecraft/versions/1.10.2-Mod-Local/mods/CoFHCore-1.10.2-4.1.9.13-universal.jar!/cofh/api/energy/IEnergyProvider.class
>                   * RF API class 'IEnergyReceiver' is loaded from: jar:file:/F:/.minecraft/versions/1.10.2-Mod-Local/mods/CoFHCore-1.10.2-4.1.9.13-universal.jar!/cofh/api/energy/IEnergyReceiver.class
>                   * RF API class 'IEnergyStorage' is loaded from: jar:file:/F:/.minecraft/versions/1.10.2-Mod-Local/mods/CoFHCore-1.10.2-4.1.9.13-universal.jar!/cofh/api/energy/IEnergyStorage.class
>                   * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/F:/.minecraft/versions/1.10.2-Mod-Local/mods/CoFHCore-1.10.2-4.1.9.13-universal.jar!/cofh/api/energy/ItemEnergyContainer.class
>                   * RF API class 'TileEnergyHandler' is loaded from: jar:file:/F:/.minecraft/versions/1.10.2-Mod-Local/mods/CoFHCore-1.10.2-4.1.9.13-universal.jar!/cofh/api/energy/TileEnergyHandler.class
> 	Detailed Tesla API diagnostics:
>                   * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
>                   * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
>                   * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
>                   * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
>                   * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
>                   * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
>                   * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
>                   * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
>                   * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
>                   * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
>                   * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)
> 
> 	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> 	!!!You are looking at the diagnostics information, not at the crash. Scroll up!!!
> 	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> 
> 	EnderStorage Invalid Fingerprint Reports: 
> 	AE2 Integration: IC2:ON, RC:OFF, RF:OFF, RFItem:OFF, MFR:OFF, Waila:ON, InvTweaks:OFF, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF
> 	Profiler Position: N/A (disabled)
> 	Player Count: 1 / 8; [GCEntityPlayerMP['Hinyari_Gohan'/879, l='うんちもりもり', x=-275.68, y=72.92, z=-142.47]]
> 	Type: Integrated Server (map_client.txt)
> 	Is Modded: Definitely; Client brand changed to 'fml,forge'
> 	OptiFine Version: OptiFine_1.10.2_HD_U_D8
> 	Render Distance Chunks: 8
> 	Mipmaps: 0
> 	Anisotropic Filtering: 1
> 	Antialiasing: 0
> 	Multitexture: false
> 	Shaders: null
> 	OpenGlVersion: 4.3.0 - Build 20.19.15.4624
> 	OpenGlRenderer: Intel(R) HD Graphics 4600
> 	OpenGlVendor: Intel
> 	CpuCount: 8
```

**Comment by boq** [comment] 2017-07-01 18:43
Should be fixed (at least this crash, couldn't reproduce whole scenario).

**Closed by boq** 2017-07-01 18:43 UTC
